title: Tmtomer Site
author: tmtomer
email: trevor.tomer@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  My awesome site

# social links
github_username:  tmtomer # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
